spring.datasource.url=jdbc:postgresql://ep-lucky-term-amd9tweb-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_x9ciFYHfg6Ed
spring.datasource.driver-class-name=org.postgresql.Driver